name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
    
      - name: Upload Mochawesome report
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: mochawesome-report
            path: cypress/reports
   
      - name: Upload Cypress artifacts (videos, screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots

      - name: Notify (log only)
        if: always()
        run: |
            status="${{ job.status }}"
            if [ "$status" == "success" ]; then
            echo "✅ Cypress tests PASSED"
            else
            echo "❌ Cypress tests FAILED"
            fi
            
      - name: Send test result email
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.GMAIL_USER }}
            password: ${{ secrets.GMAIL_APP_PASSWORD }}
            subject: "GitHub Actions - Cypress Test Results"
            to: tu-email-para-recibir@gmail.com
            from: ${{ secrets.GMAIL_USER }}
            body: |
                Cypress tests have completed. Check the report attached or in the artifacts.
