name: Run Cypress Tests and Deploy Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run

      - name: Prepare HTML report for GitHub Pages
        if: always()
        run: |
          mkdir public
          cp -r cypress/reports/html/* public/

      - name: Upload report to GitHub Pages
        if: always()
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

  deploy:
    needs: cypress-run
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
